title: MY BLOG
logo: /assets/img/logo.png
email: adithprasetio@yahoo.com
description: Blog yang sengaja saya buat untuk dokumentasi apa yang saya pelajari pada saat pkl
show_downloads: false
google_analytics: UA-108144808-1
theme: jekyll-theme-cayman
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
